<?php

require_once __ROOT_DIR__.'/shipsay/configs/filter.ini.php';
// [MODLOG 2026-02-12] 兜底补章：缺章/短章时读取补丁表并可远端拉取
require_once __ROOT_DIR__.'/shipsay/include/chapter_patch.php';
$now_pid=1;
$articleid=$sourceid=$matches[1];
if($is_acode)
{
	$sql='SELECT articleid FROM '.$dbarr['pre'].'article_article WHERE articlecode = "'.$sourceid.'"';
	$sourceid=$db->ss_getone($sql)['articleid'];
}
$cid_raw=$matches[2];
$chapterid=$sourcecid=$cid_raw;
if(isset($matches[3]))$now_pid=str_replace('_','',$matches[3]);
$legacy_sourcecid=null;
if($is_multiple)
{
	$sourceid=ss_sourceid($sourceid);
	// use_orderid=1 时，URL里的 cid 是 chapterorder（不参与混淆解混淆）
	if(!$use_orderid)
	{
		$sourcecid=ss_sourceid($sourcecid);
	}
	else
	{
		// 兼容旧链接：旧模式 cid=混淆后的 chapterid
		$legacy_sourcecid=ss_sourceid($cid_raw);
	}
}
else
{
	if($use_orderid)
	{
		// 非混淆站点也可能存在旧 chapterid 链接
		$legacy_sourcecid=(int)$cid_raw;
	}
}
$max_pid=1;
$prevpage_url='';
$nextpage_url='';
$subaid=intval($sourceid/1000);
$sql=$rico_sql.'AND articleid = '.$sourceid;
if(isset($redis))
{
	$infoarr=$redis->ss_redis_getrows($sql,$cache_time);
}
else
{
	$infoarr=$db->ss_getrows($sql);
}
if(!is_array($infoarr) || empty($infoarr) || !isset($infoarr[0])) Url::ss_errpage();
$articlename=$infoarr[0]['articlename'];
$author=$infoarr[0]['author'];
$author_url=$infoarr[0]['author_url'];
$img_url=$infoarr[0]['img_url'];
$sortid=$infoarr[0]['sortid'];
$sortname=$infoarr[0]['sortname'];
$sorturl=Sort::ss_sorturl($sortid);
$isfull=$infoarr[0]['isfull'];
$keywords=$infoarr[0]['keywords'];
$words_w=$infoarr[0]['words_w'];
$intro_des=$infoarr[0]['intro_des'];
$intro_p=$infoarr[0]['intro_p'];
if(isset($redis)&&$redis->ss_get($uri))
{
	$ret=$redis->ss_get($uri);
	$chapterids=$ret['chapterids'];
	$chaptername=$ret['chaptername'];
	$chapterwords=$ret['chapterwords'];
	$lastupdate=$ret['lastupdate'];
}
else
{
	$sql='SELECT chapterid,chapterorder,chaptername,'.$dbarr['words'].',lastupdate FROM '.$dbarr['pre'].$db->get_cindex($sourceid).' WHERE articleid = '.$sourceid.' AND chaptertype = 0 ORDER BY chapterorder ASC';
	$res=$db->ss_query($sql);
	$chapterorder_real=0;
	$chapterid_real=0;
	if(!$res->num_rows)Url::ss_errpage();
	while($row=mysqli_fetch_assoc($res))
	{
		$chapterids[]=$_compare_id=$use_orderid?$row['chapterorder']:$row['chapterid'];
		$matched=0;
		$need_301=0;
		$redirect_orderid=0;
		if($use_orderid)
		{
			if((int)$sourcecid===(int)$row['chapterorder'])
			{
				$matched=1;
			}
			elseif($legacy_sourcecid!==null && (int)$legacy_sourcecid===(int)$row['chapterid'])
			{
				$matched=1;
				$need_301=1;
				$redirect_orderid=(int)$row['chapterorder'];
			}
		}
		else
		{
			if($sourcecid==$_compare_id)$matched=1;
		}
		if($matched)
		{
			$txt_sourceid=$row['chapterid'];
			$chapterorder_real=(int)$row['chapterorder'];
			$chapterid_real=(int)$row['chapterid'];
			$chaptername=Text::ss_toutf8($row['chaptername']);
			if($is_ft)$chaptername=Convert::jt2ft($chaptername);
			$chapterwords=round($row[$dbarr['words']]/2);
			$lastupdate=$row['lastupdate'];
			if($use_orderid && $need_301 && $redirect_orderid>0)
			{
				// 旧链接（混淆 chapterid）-> 新链接（chapterorder）
				$loc=$now_pid>1?Url::chapter_url($articleid,$redirect_orderid,$now_pid):Url::chapter_url($articleid,$redirect_orderid);
				header('Location: '.$loc,true,301);
				exit;
			}
		}
	}
	if($use_orderid && (int)$chapterorder_real<=0)
	{
		// 未找到 chapterorder（新链接）或 chapterid（旧链接）匹配
		Url::ss_errpage();
	}
	if(isset($redis))
	{
		$ret=['chapterids'=>$chapterids,'chaptername'=>$chaptername,'chapterwords'=>$chapterwords,'lastupdate'=>$lastupdate];
		$redis->ss_setex($uri,$cache_time,$ret);
	}
}
$info_url=Url::info_url($articleid);
$index_url=Url::index_url($articleid);
$pre_cid=0;
$next_cid=0;
$chapters=count($chapterids);
$offset=array_search($sourcecid,$chapterids);
$offset==0?$pre_cid=0:$pre_cid=$chapterids[$offset-1];
$offset==$chapters-1?$next_cid=0:$next_cid=$chapterids[$offset+1];
if($pre_cid==0)
{
	$pre_url=$info_url;
}
else
{
	$tmpvar=$use_orderid?$pre_cid:($is_multiple?ss_newid($pre_cid):$pre_cid);
	$pre_url=Url::chapter_url($articleid,$tmpvar);
}
if($next_cid==0)
{
	$next_url=$info_url;
}
else
{
	$tmpvar=$use_orderid?$next_cid:($is_multiple?ss_newid($next_cid):$next_cid);
	$next_url=Url::chapter_url($articleid,$tmpvar);
}
if($use_orderid)
{
	$txtfile=$txt_url.'/'.$subaid.'/'.$sourceid.'/'.$txt_sourceid.'.txt';
}
else
{
	$txtfile=$txt_url.'/'.$subaid.'/'.$sourceid.'/'.$sourcecid.'.txt';
}
$content=Text::ss_get_contents($txtfile);
$need_patch = (strlen($content)===0||stripos($content,'not found'));
if(!$need_patch)
{
	$content=Text::ss_toutf8($content);
	$content=preg_replace('#<br\s*/?>#isU',"\r\n",$content);
	if(ss_cp_is_short($content,$chapter_patch_min_len))$need_patch=1;
}
else
{
	$content='';
}
if($need_patch)
{
	// 兜底：补丁表 -> Hub sources -> 远端 chapter_get（写回补丁表）
	$fb=ss_cp_get_or_fetch($sourceid,$chapterorder_real,$articlename,$author,$chaptername);
	if(strlen($fb)>0)
	{
		$content=Text::ss_toutf8($fb);
		$content=preg_replace('#<br\s*/?>#isU',"\r\n",$content);
	}
	else
	{
		$content='';
	}
}
switch($readpage_split_mode)
{
	case 1:if($readpage_split_lines<count(explode("\n",$content)))
	{
		$content_arr=Text::readpage_split($content);
		$max_pid=count($content_arr);
		if($now_pid>$max_pid)$now_pid=$max_pid;
		if($now_pid<1)$now_pid=1;
		$rico_content=$content_arr[$now_pid-1];
		if($now_pid>1)
		{
			if($now_pid==2)
			{
				$prevpage_url=Url::chapter_url($articleid,$chapterid);
			}
			else
			{
				$prevpage_url=Url::chapter_url($articleid,$chapterid,($now_pid-1));
			}
		}
		if($now_pid<$max_pid)
		{
			$nextpage_url=Url::chapter_url($articleid,$chapterid,($now_pid+1));
		}
	}
	else
	{
		$rico_content=Text::ss_txt2p($content);
	}
	break;
	case 2:$allwords=mb_strlen($content);
	$max_pid=ceil($allwords/$readpage_split_lines);
	if($now_pid>$max_pid)$now_pid=$max_pid;
	if($now_pid<1)$now_pid=1;
	$rico_content=Text::ss_txt2p(mb_substr($content,($now_pid-1)*$readpage_split_lines,$readpage_split_lines));
	if($now_pid>1)
	{
		if($now_pid==2)
		{
			$prevpage_url=Url::chapter_url($articleid,$chapterid);
		}
		else
		{
			$prevpage_url=Url::chapter_url($articleid,$chapterid,($now_pid-1));
		}
	}
	if($now_pid<$max_pid)
	{
		$nextpage_url=Url::chapter_url($articleid,$chapterid,($now_pid+1));
	}
	break;
	default:$rico_content=Text::ss_txt2p($content);
	break;
}
if($ShipSayFilter['is_filter'])$rico_content=Text::ss_filter($rico_content,$ShipSayFilter['filter_ini']);
if($is_ft)$rico_content=Convert::jt2ft($rico_content);
$reader_des=mb_substr(preg_replace('/<\/?p>/is','',$rico_content),0,200);
if($is_attachment&&!empty($att_url)&&$now_pid==$max_pid)
{
	$att_chapterid=$use_orderid?$txt_sourceid:$sourcecid;
	$sql='SELECT attachment FROM '.$dbarr['pre'].$db->get_cindex($sourceid).' WHERE chapterid = '.$att_chapterid;
	if(isset($redis)&&$redis->ss_get($sql))
	{
		$res=$redis->ss_get($sql);
	}
	else
	{
		$res=$db->ss_getone($sql);
		if(isset($redis))$redis->ss_setex($sql,$cache_time,$res);
	}
	$att_url.='/'.$subaid.'/'.$sourceid.'/'.$att_chapterid;
	$attHtml='';
	$regex='/\"postfix\";s:3:\"(.+?)\".+?\"attachid\";i:(\d+?);/i';
	preg_match_all($regex,$res['attachment'],$atts);
	foreach($atts[2]as $k=>$v)
	{
		$attHtml.='<img class="ss-image-content" src="'.$att_url.'/'.$v.'.'.$atts[1][$k].'"/>';
	}
	$rico_content.=$attHtml;
}
if(strlen($rico_content)<=0)
{
	if(!isset($chaptername))$chaptername=$chapterwords=$lastupdate='';
	$rico_content='章节内容缺失或章节不存在！请稍后重新尝试！';
}
if(isset($_REQUEST['json']))
{
	echo json_encode($rico_content,JSON_UNESCAPED_UNICODE);
}
else
{
	header('Last-Modified: '.date('D, d M Y H:i:s',$lastupdate-8*60*60).' GMT');
	require_once __THEME_DIR__.'/tpl_reader.php';
}